# Generated by Django 4.2 on 2023-04-16 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestcomment',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='host_reservation_guest', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='guestcomment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_reservation_guest', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='propertycomment',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='host_reservation_property', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='propertycomment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_reservation_property', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='guestcomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_comment_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='propertycomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_comment_author', to=settings.AUTH_USER_MODEL),
        ),
    ]
