# Generated by Django 4.2 on 2023-04-17 01:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0002_guestcomment_host_guestcomment_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyrating',
            name='reservation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservation_rating', to='webpages.reservation'),
        ),
        migrations.AlterField(
            model_name='propertyrating',
            name='rating',
            field=models.PositiveIntegerField(default=None, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
