# Generated by Django 4.2 on 2023-04-17 19:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0004_propertyrating_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(default=None, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('host_rater', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='host_guest_rating', to=settings.AUTH_USER_MODEL)),
                ('reservation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservation_guest_rating', to='webpages.reservation')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_guest_rating', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
