# Generated by Django 4.2 on 2023-04-18 17:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0005_guestrating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userhistory',
            name='comment_for_this_user',
        ),
        migrations.RemoveField(
            model_name='userhistory',
            name='content',
        ),
        migrations.AddField(
            model_name='userhistory',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='host_user_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userhistory',
            name='posted_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userhistory',
            name='rating',
            field=models.PositiveIntegerField(default=None, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='userhistory',
            name='reservation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservation_user_history', to='webpages.reservation'),
        ),
        migrations.AddField(
            model_name='userhistory',
            name='text_content',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='userhistory',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_user_history', to=settings.AUTH_USER_MODEL),
        ),
    ]
