# Generated by Django 4.2 on 2023-04-19 03:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0006_remove_userhistory_comment_for_this_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhistory',
            name='rating',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
